FROM tensorflow/tensorflow:2.17.0-gpu AS tensorflow

# Install basic dependencies
RUN apt-get update && apt-get install -y git cmake build-essential wget make rsync libhdf5-dev && rm -rf /var/lib/apt/lists/*

# Create user and set up work environment
RUN useradd gamma
USER gamma
WORKDIR /home/gamma

# Copy requirements file
COPY requirements.txt /home/gamma/requirements.txt

# Install Python dependencies via pip from the requirements file
RUN pip install -r /home/gamma/requirements.txt

# Setup directories
USER root
RUN mkdir /shared_dir /data01 /data02 && chown -R gamma:gamma /shared_dir /data01 /data02

USER gamma
RUN mkdir /home/gamma/workspace

# Add path to jupyter-lab to the env variable PATH
ENV PATH="$PATH:/home/gamma/workspace/anaconda3/bin:/home/gamma/.local/bin"
